- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
with examples of what metadata, observations, and forecasts will look like
closes #12
> add the dataclasses for object metadata and conftest

- .codecov.yml
- .coverage.rc
- README.md
- azure-pipelines.yml
following
https://blog.codecov.io/2019/01/24/new-in-codecov-4-4-3/
https://github.com/codecov/example-azure-pipelines
The pvlib travis config pip installs codecov instead. I don't know why the azure spec is different. https://github.com/pvlib/pvlib-python/blob/master/.travis.yml#L82-L86
starting with the pvlib .codecov.yml file. not sure if the nested test spec will work (`- "solarforecastarbiter/**/tests/.*"`)
> add codecov

- .lgtm.yml
- README.md
https://lgtm.com/projects/g/SolarArbiter/solarforecastarbiter-core/overview/
also enabled pull request review integration in github organization settings
> add lgtm integration

- .readthedocs.yml
Unfortunately, RTD calls `pip install .` with `--ignore-installed`, effectively ignoring the requirements file specs for anything that's loosely spec'ed in `setup.py`. The work around is to use `setuptools` instead.
See https://github.com/rtfd/readthedocs.org/issues/3025 for more.
Builds on my fork: https://wholmgren-solarforecastarbiter-core.readthedocs.io/en/latest/
> use setuptools on readthedocs

- README.md
adds badge and doc section to read me. also an excuse to test if the webhook is really working after creating a new url on RTD (the test webhook finally returned 200 instead of 400).
closes #3
> update readme with doc links

- setup.py
- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
Adds interval_length to datamodel.Observation. 
Removes python 3.6 from `setup.py` classifiers. This should have been removed when we decided on using `dataclass` in #14.
> add interval_length to datamodel.Observation

- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
We decided a few weeks ago that we'd add support for simple loss factors to the PV system metadata. This PR will add the support.
However, it does not currently work due because `dataclass` does not allow one to use keyword arguments in a parent class and positional arguments in a child class. See [this stack overflow]q/a(https://stackoverflow.com/questions/51575931/class-inheritance-in-python-3-7-dataclasses) for more. 
@alorenzo175 thoughts on what do here? Loss factor mix-in? No defaults?
> add loss factors to datamodel.PVModelingParameters

- azure-pipelines.yml
- docs/source/api.rst
- docs/source/reference_forecasts.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/io/nwp.py
- solarforecastarbiter/reference_forecasts/forecast.py
- solarforecastarbiter/reference_forecasts/main.py
- solarforecastarbiter/reference_forecasts/models.py
- solarforecastarbiter/reference_forecasts/tests/test_forecast.py
- solarforecastarbiter/reference_forecasts/tests/test_main.py
- solarforecastarbiter/reference_forecasts/tests/test_models.py
~This PR is a total mess and is in no shape to merge.~ Starting to hack at #10. 
Rough idea is:
* `main.py`: glue code
* `models.py`: predefined processing functions for each standard model
* `forecast.py`: library functions that don't care about the model
I started by writing `forecast.py` and got frustrated that it was divorced from models. So then I started writing `models.py` and got frustrated that it was divorced from the workflow. So then I started writing `main.py` and got frustrated that I didn't understand the workflow and the "only calculate solar position once" mantra felt awkward in places. 
It's not clear to me if `main.py` should live at this level or at a higher level. I'm not a big fan of the potential `solarforecastarbiter.io` import in this module at this subpackage …
> benchmark nwp forecasts initial implementation

- solarforecastarbiter/io/fetch/__init__.py
- solarforecastarbiter/io/fetch/nwp.py
to not rely on a complicated bash script and to limit the number of simultaneous requests to nomads
> adjust fetch/nwp.py

- solarforecastarbiter/io/fetch/nwp.py
- solarforecastarbiter/io/fetch/tests/test_nwp.py
NFS can cause all kinds of issues especially for GEFS that needs to download and remove thousands of files. So add better error logging, add the option to use /tmp to save the grib files, and execute the wgrib2 code in the worker process instead of the main thread
> better nwp error handling and remove files in loop

- solarforecastarbiter/io/fetch/__init__.py
- solarforecastarbiter/io/fetch/nwp.py
For fetching nwp forecasts. This has been running for 3 weeks with no issues or pod restarts.
> Add a dedicated timeout to the aiohttp client

- solarforecastarbiter/conftest.py
- solarforecastarbiter/io/api.py
- solarforecastarbiter/io/fetch/sandia.py
- solarforecastarbiter/io/fetch/tests/test_sandia.py
- solarforecastarbiter/io/reference_observations/common.py
- solarforecastarbiter/io/reference_observations/crn.py
- solarforecastarbiter/io/reference_observations/midc_config.py
- solarforecastarbiter/io/reference_observations/reference_data.py
- solarforecastarbiter/io/reference_observations/sandia.py
- solarforecastarbiter/io/reference_observations/solrad.py
- solarforecastarbiter/io/reference_observations/srml.py
- solarforecastarbiter/io/reference_observations/surfrad.py
- solarforecastarbiter/io/reference_observations/tests/test_common.py
- solarforecastarbiter/io/reference_observations/tests/test_reference_data.py
- solarforecastarbiter/io/tests/test_api.py
To help when running often. Includes:
- avoid getting each site individually when listing observations
- don't create duplicate observations/sites on init
- better error handling
> Improvments to reference data

- MANIFEST.in
Changes the manifest strategy so that all tests and data files are included by default. Styled after the pvlib python `MANIFEST.in`, which is styled after the pandas `MANIFEST.in`. The philosophy is better to include too much than not enough. 
Ran into this when trying to access NWP test data files for Denver workshop reference forecast notebook.
> expand manifest to include tests, data files

- solarforecastarbiter/io/tests/test_api.py
won't pass until https://github.com/SolarArbiter/solarforecastarbiter-api/issues/128 is resolved
> test that get/post observation/forecast account for tz correctly

- docs/source/whatsnew/1.0.0b.rst
- solarforecastarbiter/cli.py
- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/reports/figures.py
- solarforecastarbiter/reports/main.py
- solarforecastarbiter/reports/metrics.py
- solarforecastarbiter/reports/template.py
- solarforecastarbiter/reports/templates/head.html
> convert resampled obs, fx to site tz

- docs/source/whatsnew/1.0.0b.rst
- solarforecastarbiter/io/tests/test_api.py
- solarforecastarbiter/io/tests/test_io_utils.py
- solarforecastarbiter/io/utils.py
There are a couple of additional places in the code that use `.loc[start:end]` but they are not likely to be passed inconsistent timezones, so I don't think this is worth handling more generally.
> slice with consistent tz

- docs/source/whatsnew/1.0.0b.rst
- solarforecastarbiter/reports/figures.py
Works with 3 long names. 4 is too much. Note that the table now shows all of the forecasts and metrics (at least for 4 forecasts).
> bigger metrics table, summary graphics

- docs/source/whatsnew/1.0.0b.rst
- solarforecastarbiter/reports/metrics.py
- solarforecastarbiter/reports/tests/test_metrics.py
also closes https://github.com/SolarArbiter/solarforecastarbiter-api/issues/148/
> handle when fx or obs are empty in current calculate metrics

- docs/source/whatsnew/1.0.0b.rst
- solarforecastarbiter/io/api.py
- solarforecastarbiter/io/tests/test_api.py
- solarforecastarbiter/io/tests/test_io_utils.py
- solarforecastarbiter/io/utils.py
> add decorator so Api can accept str or time obj start/end

- docs/source/api.rst
- docs/source/whatsnew/1.0.0b.rst
- solarforecastarbiter/metrics/deterministic.py
- solarforecastarbiter/metrics/tests/test_deterministic.py
- solarforecastarbiter/reports/metrics.py
Add (standalone) functions for computing deterministic forecast error metrics to the `metrics` subpackage, including adding tests and updating the `reports` subpackage to use the functions. There are other metrics and functionality to be added to the `metrics` subpackage, but those will be addressed in future PRs.
Also, the commits from this PR could be squashed prior to merging.
> Add deterministic metrics

- docs/source/api.rst
- docs/source/whatsnew/1.0.0b.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/io/tests/test_api.py
- solarforecastarbiter/tests/test_datamodel.py
@alorenzo175 is this how we want to implement probabilistic forecasts in `datamodel.py`? I've forgotten what we discussed months ago.
I'll add tests once we agree on the design.
> add probabilistic forecast classes to datamodel

- docs/source/whatsnew/1.0.0b.rst
- solarforecastarbiter/cli.py
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/tests/test_datamodel.py
> fix non-tuple default report filter

- docs/source/api.rst
- docs/source/whatsnew/1.0.0b.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/io/api.py
- solarforecastarbiter/io/tests/test_api.py
@lboeman see the note in `get_probabilistic_forecast_constant_value` regarding https://github.com/SolarArbiter/solarforecastarbiter-api/issues/158
> add probabilistic forecasts to APISession

- docs/source/whatsnew/1.0.0b.rst
- solarforecastarbiter/io/reference_observations/common.py
- solarforecastarbiter/io/reference_observations/crn.py
- solarforecastarbiter/io/reference_observations/tests/test_common.py
> Reindex reference observations to interval_length before posting

- docs/source/api.rst
- docs/source/whatsnew/1.0.0b2.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/io/api.py
- solarforecastarbiter/io/tests/test_api.py
- solarforecastarbiter/tests/test_datamodel.py
Adds the aggregate object to the datamodel. We'll also need to allow forecasts to reference an aggregate instead of a site. The question is how should we do that? One option is to add aggregate as a parameter and then either site or aggregate will be None (or some missing value), or make a new AggregateForecast object where aggregate replaces site. I'm leaning towards a separate object (and separate probabilistic object) since processing an aggregate forecast will be quite different in e.g. making a report. Thoughts @wholmgren
> Add aggregates to datamodel

- docs/source/api.rst
- docs/source/whatsnew/1.0.0b2.rst
- requirements.txt
- solarforecastarbiter/metrics/deterministic.py
- solarforecastarbiter/metrics/tests/test_deterministic.py
Initial attempt at adding the KSI, OVER and CPI metrics for deterministic forecasts. These metrics are based on the (empirical) CDFs of the forecasts and observations, which make it a big more complicated to test (compared to MAE, MBE, etc.).
A couple discussion points:
- Thoughts on the function names? I went with more verbose naming to avoid name conflicts between functions and values (e.g. avoid `ksi = metrics.ksi(y_true, y_pred)`), but the current functions may be too verbose.
- Can someone check that I'm not making a dumb mistake with how I'm computing the empirical CDFs? See the `_estimate_cdf()` function in the `deterministic.py` file for details, but the current code 1) computes the CDFs for the observations and forecasts and then 2) linearly interpolates the two CDFs to the same …
> Metrics: add KSI, OVER, CPI

- docs/source/whatsnew/1.0.0b2.rst
- solarforecastarbiter/reports/figures.py
- solarforecastarbiter/reports/main.py
- solarforecastarbiter/reports/template.py
old:
new:
notice that in the new plot the hourly observation data is properly colored black instead of gray.
> fix processed fx obs handling in timeseries, scatter

- docs/source/whatsnew/1.0.0b2.rst
- setup.py
- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/io/api.py
- solarforecastarbiter/io/reference_observations/common.py
- solarforecastarbiter/io/reference_observations/crn.py
- solarforecastarbiter/io/reference_observations/default_forecasts.py
- solarforecastarbiter/io/reference_observations/midc.py
- solarforecastarbiter/io/reference_observations/rtc.py
- solarforecastarbiter/io/reference_observations/solrad.py
- solarforecastarbiter/io/reference_observations/srml.py
- solarforecastarbiter/io/reference_observations/surfrad.py
- solarforecastarbiter/io/reference_observations/tests/test_common.py
- solarforecastarbiter/reference_forecasts/main.py
- solarforecastarbiter/reference_forecasts/models.py
- solarforecastarbiter/reference_forecasts/tests/test_main.py
- solarforecastarbiter/tests/test_datamodel.py
Enable the creation of reference ProbabilisticForecast objects for MIDC, SOLRAD, SURFRAD, and RTC sites, and scheduled updates using GEFS. API calls to ``list_probabilistic_forecasts`` should also be a bit faster since we don't really need to get each constant value from the API.
Also closes #205.
> Add GEFS reference forecasts for select networks

- docs/source/whatsnew/1.0.0b2.rst
- solarforecastarbiter/reports/figures.py
- solarforecastarbiter/reports/template.py
- solarforecastarbiter/reports/tests/test_figures.py
> handle long names in report figures and tables

- docs/source/whatsnew/1.0.0b2.rst
- solarforecastarbiter/reports/figures.py
Moves the scatter plot's legend to its own figure layout and dynamically determines the `plot_width` so the aspect ratio remains (nearly) 1:1 (see figures below). 
Not sure what to do about the time series plot. Could use the same approach. Some might argue the widest possible plot is better even if it means some of the plot is obscured and pan/zoom let's you position the data window to see things. Bigger problem is what to do about too many legend items for the box. I am guessing it won't be possible to address this without distorting the aspect ratio. Maybe reduce font size.
Unfortunately, bokeh does not support linking legends to multiple figures.
I miss matplotlib.
got any better ideas @alorenzo175?
> improve legend layout

- docs/source/whatsnew/1.0.0b2.rst
- solarforecastarbiter/reports/figures.py
- solarforecastarbiter/reports/tests/test_figures.py
> retain forecast order in metric cds creation

- docs/source/api.rst
- docs/source/whatsnew/1.0.0b2.rst
> add missing datamodel.Report and more classes to api.rst

- docs/source/api.rst
- docs/source/whatsnew/1.0.0b3.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/io/api.py
- solarforecastarbiter/io/tests/test_api.py
- solarforecastarbiter/reference_forecasts/main.py
- solarforecastarbiter/reference_forecasts/tests/test_main.py
- solarforecastarbiter/reports/main.py
- solarforecastarbiter/reports/tests/test_reports_main.py
- solarforecastarbiter/tests/test_datamodel.py
- solarforecastarbiter/validation/tasks.py
- solarforecastarbiter/validation/tests/test_validation_tasks.py
Primarily adjusts the functions to make reference nwp forecasts and the daily observation validation to only apply to forecasts/observation in the same organization as the user executing said functions. This is required for the scheduled job executors that only alter data within their organization. The adjustments also required that the provider parameter be added to the datamodel objects that were missing it. 
Also fix the assumption that the first filter in a report is a quality flag filter.
> Adjust functions that will be used in scheduled jobs

- docs/source/whatsnew/1.0.0b3.rst
- solarforecastarbiter/metrics/deterministic.py
- solarforecastarbiter/metrics/probabilistic.py
- solarforecastarbiter/metrics/tests/test_deterministic.py
- solarforecastarbiter/metrics/tests/test_probabilistic.py
Work on standardizing the naming and ordering conventions for inputs to all metric functions:
- naming: `obs` = observations, `fx` = forecasts
- order: `obs` then `fx` then other inputs (e.g. `obs, fx, norm`)
> metrics: standardize input naming + ordering

- docs/source/api.rst
- docs/source/whatsnew/1.0.0b3.rst
- solarforecastarbiter/metrics/tests/test_valuation.py
- solarforecastarbiter/metrics/valuation.py
This PR is focused on adding some forecast valuation metrics for quantifying the monetary cost of forecast errors. Note: the name (`solarforecastarbiter.metrics.valuation`) was chosen to avoid namespace conflicts with the (more commonly used terms) `cost` and `value`
> metrics: add valuation metrics

- docs/source/api.rst
- docs/source/whatsnew/1.0.0b3.rst
- solarforecastarbiter/metrics/deterministic.py
- solarforecastarbiter/metrics/tests/test_deterministic.py
Add normalized MAE and MBE (NMAE and NMBE) to the deterministic metrics as separate functions (same format as normalized RMSE (NRMSE)).
> metrics: deterministic: add NMAE and NMBE

- docs/source/api.rst
minor edits to metrics subsection of API docs.
> add subsubsections to metrics api doc

- solarforecastarbiter/metrics/tests/test_deterministic.py
This PR adds tests so that all metrics have non-zero examples.
> metrics: add additional tests

- solarforecastarbiter/metrics/deterministic.py
- solarforecastarbiter/metrics/probabilistic.py
Complete `_MAP`, `_REQ_REF_FX`, and `_REQ_NORM` in both the deterministic and probabilistic metrics.
> metrics: complete `_MAP`, `_REQ_REF_FX`, `_REQ_NORM`

- solarforecastarbiter/metrics/deterministic.py
- solarforecastarbiter/metrics/tests/test_deterministic.py
This PR adds exception handling to `solarforecastarbiter.metrics.deterministic.pearson_correlation_coeff()` to deal with cases where a) `len(obs) < 2` or `len(fx) < 2` or b) `len(obs) != len(fx)`. In those two cases, the function returns NaN.
> metrics: handle exceptions in pearson_correlation_coeff

- docs/source/whatsnew/1.0.0b3.rst
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/metrics/calculator.py
- solarforecastarbiter/metrics/deterministic.py
- solarforecastarbiter/metrics/probabilistic.py
Adds an `ALLOWED_DETERMINISTIC_METRICS` and `ALLOWED_PROBABILISTIC_METRICS` dictionaries mapping abbreviated names to display names. e.g. 'mae' => 'mae', so that we can import this elsewhere without touching the private `_MAP` variable in metrics modules, and so that there is a centralized location to define display names for each metric.
> Add metrics mappings to data model

- solarforecastarbiter/conftest.py
- solarforecastarbiter/metrics/preprocessing.py
- solarforecastarbiter/metrics/tests/test_preprocessing.py
- solarforecastarbiter/tests/test_cli.py
Modify `resample_and_align()` to explicitly drop any timestamps where there is either a NaN in the observation or forecast time-series.
This partially solves #285 by explicitly dropping timestamps where there is a NaN in either the observations or forecasts.
> metrics: preprocessing: drop NaNs explicitly

- solarforecastarbiter/metrics/summary.py
- solarforecastarbiter/metrics/tests/test_summary.py
This PR adds `solarforecastarbiter.metrics.summary`, which contains functions for computing summary statistics of observations/forecasts (e.g. min, max, mean and std). These summary statistics will eventually be incorporated into the report interface (which will be addressed in subsequent PRs).
> metrics: add summary statistics

- docs/source/whatsnew/1.0.0b4.rst
- solarforecastarbiter/metrics/preprocessing.py
- solarforecastarbiter/metrics/tests/test_preprocessing.py
> metrics: preprocessing: handle empty obs Series

- docs/source/whatsnew/1.0.0b4.rst
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/tests/test_datamodel.py
Adds helper function `__check_metrics__()` to determine if the select metrics are valid (e.g. if evaluating a deterministic forecast, then should use deterministic forecast metrics, not probabilistic).
> datamodel: add `__check_metrics__()`

- docs/source/whatsnew/1.0.0b4.rst
- solarforecastarbiter/metrics/calculator.py
- solarforecastarbiter/metrics/tests/test_calculator.py
- solarforecastarbiter/reports/figures.py
**EDIT**: This PR was originally made to revise the hourly category labels based on whether `interval_label == ending` or `interval_label == beginning`. As the result of discussions in this PR, email, etc., this PR has now morphed to be more generally aimed at revising how the `metrics.calculator` handles the `interval_label` attribute of the `obs`/`fx`. Hence why I've revised the PR title.
> metrics: calculator: handle ending interval label

- docs/source/whatsnew/1.0.0b4.rst
- solarforecastarbiter/metrics/preprocessing.py
- solarforecastarbiter/metrics/tests/test_preprocessing.py
Add a note to the docstring of `resample_and_align()` regarding the behavior in the case of the `interval_label` not being the same between the forecast and observation. Also revise tests to explicitly check this behavior.
Note: this behavior is likely to be revised in the future; the goal of this commit is to document the current behavior as a first step towards revising the behavior.
> metrics: preprocessing: clarify `interval_label` mismatch behavior

- docs/source/whatsnew/1.0.0b4.rst
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/tests/test_datamodel.py
This PR is meant to add support for checking whether the selected metrics are valid for probabilistic forecasts via the `datamodel.__check__metrics()` function. Per the discussion last week, this PR is to be merged against the 1.0beta4` branch (instead of `master`).
> datamodel.__check__metrics(): support probabilistic forecasts

- docs/source/api.rst
- docs/source/whatsnew/1.0.0b4.rst
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/reports/figures.py
- solarforecastarbiter/reports/main.py
- solarforecastarbiter/reports/template.py
- solarforecastarbiter/reports/tests/test_macros.py
To  be merged following #305, I updated docstrings in the reports module and added parameters for all non-private objects found in datamodel. There are some spotty linking issues in the sphinx rendering I hope to figure out.
> Docstrings

- solarforecastarbiter/metrics/tests/test_calculator.py
- solarforecastarbiter/metrics/tests/test_preprocessing.py
This PR adds tests for `metrics.preprocessing` and `metrics.calculator` functions to ensure that report timezones are respected when computing and reporting metric results (e.g. RMSE per hour of the day should use the timezone from the report, not the site). Based on review of the code (as noted in #298), the `metrics` functions appear to already properly convert the fx/obs pairs to the local timezone from the report. However, there were no tests that explicitly confirmed this behavior. Hence this PR.
> metrics: test timezone behavior

- docs/source/whatsnew/1.0.0b4.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/reports/main.py
- solarforecastarbiter/reports/template.py
- solarforecastarbiter/reports/templates/base.html
- solarforecastarbiter/reports/templates/body.html
- solarforecastarbiter/reports/templates/empty_base.html
- solarforecastarbiter/reports/templates/failure.html
- solarforecastarbiter/reports/templates/pending.html
- solarforecastarbiter/reports/templates/versions.html
- solarforecastarbiter/reports/tests/test_reports_main.py
- solarforecastarbiter/reports/tests/test_template.py
> template failed reports and report dicts

- azure-pipelines.yml
- docs/source/whatsnew/1.0.0b5.rst
- solarforecastarbiter/reports/figures.py
- solarforecastarbiter/reports/tests/test_figures.py
Chrome is really difficult to install and run in a docker container without giving up sandboxing, so go back to phantomjs for now but try and ensure processes get cleaned up. FIrefox is an easier option, but it is much slower. Bokeh 2.0 may have changes to the javascript that make Firefox faster to render and break phantomjs, so punt until then.
> revert to using PhantomJS but kill cleanly

- docs/source/api.rst
- docs/source/whatsnew/1.0.0b5.rst
- solarforecastarbiter/metrics/event.py
- solarforecastarbiter/metrics/tests/test_event.py
This PR adds the standalone functions for computing the deterministic event forecast metrics.
> metrics: add event forecast metrics

- solarforecastarbiter/reports/figures/plotly_figures.py
- solarforecastarbiter/reports/templates/body.html
Updates axes configuration function to accept a dict of kwargs for plotly's `Figure.update_xaxes` and `Figure.update_yaxes` function. This was to remedy the display of non-discrete values on the axes for years, but in finding the solution I also discovered that a tick delta could be supplied for the date axes and we could avoid displaying the noon ticks between days.
> discrete xaxes labels closes #363

- docs/source/whatsnew/1.0.0b5.rst
- solarforecastarbiter/cli.py
- solarforecastarbiter/io/api.py
- solarforecastarbiter/io/reference_observations/common.py
- solarforecastarbiter/io/reference_observations/midc.py
- solarforecastarbiter/io/reference_observations/rtc.py
- solarforecastarbiter/io/reference_observations/tests/test_common.py
- solarforecastarbiter/io/tests/test_api.py
- solarforecastarbiter/tests/test_cli.py
> Use last timestamp to adjust start time for update reference obs

- docs/source/api.rst
- docs/source/whatsnew/1.0.0b5.rst
- solarforecastarbiter/plotting/timeseries.py
- solarforecastarbiter/validation/quality_mapping.py
- solarforecastarbiter/validation/tasks.py
- solarforecastarbiter/validation/tests/test_quality_mapping.py
- solarforecastarbiter/validation/tests/test_validation_tasks.py
- solarforecastarbiter/validation/tests/test_validator.py
- solarforecastarbiter/validation/validator.py
> add cloudy flag to ghi and nighttime to power variables

- docs/source/api.rst
- docs/source/whatsnew/1.0.0b5.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/io/api.py
- solarforecastarbiter/io/tests/test_api.py
- solarforecastarbiter/metrics/calculator.py
- solarforecastarbiter/metrics/deterministic.py
- solarforecastarbiter/metrics/probabilistic.py
- solarforecastarbiter/metrics/tests/test_calculator.py
Besides adding support for probabilistic forecasts, I added a api function to get all forecast values in a pandas.DataFrame with constant_value as columns and timeseries filled in.  If things look good I'll add to the api documentation and whatsnew.
There is certainly some duplication between `metrics.calculate_probabilistic_metrics` and `metrics.calculate_deterministic_metrics` but with EventForecasts also tbd, I'm not sure now is the best time to refactor, but if you have ideas please let me know.
I'll start working on the support in the preprocessing now and report.
> Added probabilistic forecast support to metrics calculator

- .gitignore
- docs/source/api.rst
- docs/source/whatsnew/1.0.0b5.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/io/api.py
- solarforecastarbiter/metrics/calculator.py
- solarforecastarbiter/metrics/deterministic.py
- solarforecastarbiter/metrics/preprocessing.py
- solarforecastarbiter/metrics/tests/test_calculator.py
- solarforecastarbiter/metrics/tests/test_deterministic.py
- solarforecastarbiter/reports/templates/body.html
- solarforecastarbiter/reports/templates/metrics_meta_table.html
- solarforecastarbiter/tests/test_datamodel.py
Initial attempt at accounting for uncertainty using a deadband. Example code in details below. @alorenzo175 let me know what you think of this approach before I clean it up. I'm trying to leave some flexibility for the dashboard to say "use this deadband for all or use preset uncertainty for all". In the long run it might be nice to let the dashboard set the deadband for each, but I think that would require more refactoring in `calculator` than is in scope here.
<details>
```python
latitude = 32.2
longitude = -110.9
elevation = 700
site = datamodel.Site(
name='Tucson, AZ',
latitude=latitude,
longitude=longitude,
elevation=elevation,
timezone='America/Phoenix'
)
name = 'OASIS DA GHI'
variable = 'ghi'
fx1 = datamodel.Forecast(
name=name + ' 15',
site=site,
variable=variable, …
```
> account for uncertainty using deadband

- docs/source/whatsnew/1.0.0b5.rst
- solarforecastarbiter/metrics/calculator.py
- solarforecastarbiter/metrics/tests/test_calculator.py
> enforce metrics order

- solarforecastarbiter/reports/templates/macros.j2
- solarforecastarbiter/reports/templates/metrics_meta_table.html
- solarforecastarbiter/reports/templates/obsfx_table.html
- solarforecastarbiter/reports/tests/test_macros.py
Adds css classes to the <table> elements in reports for easier selection with css rules, to address an issue with table crowding found in #361
> add classes to report tables

- docs/source/whatsnew/1.0.0b5.rst
- solarforecastarbiter/plotting/tests/test_plotting_utils.py
- solarforecastarbiter/plotting/tests/test_timeseries.py
- solarforecastarbiter/plotting/timeseries.py
- solarforecastarbiter/plotting/utils.py
Adds ability to plot event timeseries to the plotting module. Will need to be rebased on master when #361 is merged. A screenshot of the event timeseries is as below.
> Add event timeseries support to plotting module

- docs/source/whatsnew/1.0.0b5.rst
- solarforecastarbiter/reports/figures/plotly_figures.py
This PR removes the static height setting for metric plots with the "total" category  when abbreviated names are greater than 15 characters, or there are more than 6 pairs. 
This avoids an issue with cuttoff x axis labels as seen in the screenshot below:
The PR solves the issue but has one unavoidable quirk  when few pairs exist with really long names: plotly makes room on the right of the plot to allow room for angled labels as shown below.
> Fix label cutoff for total metric plots.

- solarforecastarbiter/conftest.py
- solarforecastarbiter/io/api.py
- solarforecastarbiter/io/tests/test_api.py
- solarforecastarbiter/io/utils.py
Serializes and Deserializes `reference_forecast_values` field of ProcessedForecastObservations. This was causing a TypeError when workers tried to post a raw report to the API.
> Reference forecast value serialization

- solarforecastarbiter/metrics/preprocessing.py
- solarforecastarbiter/metrics/tests/test_preprocessing.py
> fix reference forecast alignment

- docs/source/whatsnew/1.0.0b5.rst
- solarforecastarbiter/reports/templates/body.html
- solarforecastarbiter/reports/templates/macros.j2
- solarforecastarbiter/reports/tests/test_macros.py
I think the text is better but still not great. Trying to emphasize it's the observations that are analyzed.
Existing table:
Option A:
Option B:
Option C:
Option D: (not shown because it would take more effort to change) 
* Columns: Aligned Pair, Observation, Filter 1, Filter 2, Filter 3...
> clarify data validation section

- docs/source/whatsnew/1.0.0rc1.rst
- solarforecastarbiter/metrics/calculator.py
- solarforecastarbiter/metrics/tests/test_calculator.py
> fix months and weekdays ordering

- azure-pipelines.yml
- docs/source/whatsnew/1.0.0rc1.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/reports/figures/plotly_figures.py
- solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
I want to explore how long this takes for a standard report. Full PDF generation via Latex will likely take some time to begin with (and require backend generation with some temporary storage to be retrieved by the client in another request) so might make sense to generate PDFs from the spec on a PDF report request.
> Generate PDF figures

- solarforecastarbiter/io/reference_observations/srml_reference_sites.json
I made an error in exporting json to set the correct parameters for power observations at the SRML Portland PV 30 deg site. The dc_power observations were duplicated instead of including both ac and dc measurements. The Sanyo module at that site was also left out, and is now included here. I've run this locally to initialize sites and checked that each one has the appropriate observations with the appropriate variable and extra parameters.
> Fix power observations for SRML Portland PV site.

- docs/source/whatsnew/1.0.0rc1.rst
- solarforecastarbiter/io/reference_observations/common.py
- solarforecastarbiter/io/reference_observations/srml.py
- solarforecastarbiter/io/reference_observations/srml_reference_sites.json
- solarforecastarbiter/io/reference_observations/tests/test_common.py
- solarforecastarbiter/io/reference_observations/tests/test_srml.py
- solarforecastarbiter/reference_forecasts/main.py
- solarforecastarbiter/reference_forecasts/tests/test_fx_utils.py
- solarforecastarbiter/reference_forecasts/tests/test_main.py
- solarforecastarbiter/reference_forecasts/utils.py
adds a check_persistence_compatibility function to see if a persistence forecast can be made from a forecast observation pair and then uses this function before creating reference persistence forecasts
> Avoid creating invalid reference persistence forecasts

- docs/source/api.rst
- solarforecastarbiter/io/api.py
This PR adds documentation of how to pass API calls through a proxy server and how to specify a SSL certificate. This documentation is targeted at the (possibly few) users who are running the Solar Arbiter inside a restricted network that requires passing all HTTP/HTTPS outbound requests via a proxy server. Depending on the specifics of the network and their machine, they may need to specify the proxy server and/or SSL certificate in order to, e.g., push forecast data to the Solar Arbiter dashboard for a forecast trial.
> io/api: document use of proxy servers and SSL certificates

- docs/source/api.rst
- docs/source/whatsnew/1.0.0rc1.rst
- solarforecastarbiter/reports/main.py
- solarforecastarbiter/reports/tests/test_reports_main.py
- solarforecastarbiter/validation/tasks.py
- solarforecastarbiter/validation/tests/test_validation_tasks.py
This does not add the various `validate_daily_{variable}` functions, but instead relies on using whatever immediat function is available and adding the stale and interpolated flags.
> Add default daily validation and always re-validate observations in a report

- docs/source/api.rst
- docs/source/whatsnew/1.0.0rc1.rst
- solarforecastarbiter/reference_forecasts/persistence.py
- solarforecastarbiter/reference_forecasts/tests/test_persistence.py
The goal of this PR is to add a reference probabilistic forecast method. My initial idea is to implement the Persistence Ensemble (PeEn) method [1], which is fairly commonly used as a baseline probabilistic forecast in the literature and relies solely on historical observations to estimate an empirical CDF, which is then propagated into future. Similar to (dull) persistence, this works well in short horizons and during non-changing conditions (e.g. extended periods of clear-sky or overcast weather). Also, we can implement variations of PeEn such as using clear-sky index observations (similar to "Smart Persistence") as well as matching the empirical CDF by hour of the day, which in turn would provide a similar effect as using clear-sky index but for data without clear-sky models (e.g. net …
> Add reference probabilistic forecast

- docs/source/whatsnew/1.0.0rc1.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/io/api.py
- solarforecastarbiter/io/tests/test_api.py
- solarforecastarbiter/io/tests/test_io_utils.py
- solarforecastarbiter/io/utils.py
- solarforecastarbiter/reports/figures/plotly_figures.py
- solarforecastarbiter/tests/test_cli.py
So far I have a test that reproduces the failure.
@alorenzo175 I started trying to make `serialize_timeseries` work with DataFrames and it's turning out to be less straightforward than I thought it would be. The `schema` has `'column': 'value'` - do we want to change this to `'columns': [{df.columns}]` and then `deserialize_timeseries` has some conditional on this? Or do we want to let the calling functions serialize the DataFrame column by column, and the reverse for deserialize?
I can keep hacking at this but feel free to take over if you have a good idea of what to do.
> handle serialization/deserialization for prob fx dataframes

- docs/source/whatsnew/1.0.0rc1.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/tests/test_datamodel.py
> fix prob forecast creation from raw report dict

- solarforecastarbiter/reports/template.py
- solarforecastarbiter/reports/templates/html/body.html
- solarforecastarbiter/reports/templates/html/metrics_meta_table.html
- solarforecastarbiter/reports/templates/pdf/base.tex
- solarforecastarbiter/reports/templates/pdf/macros.j2
Otherwise linking and collaps won't work for costs with things like
a space in the name.
> fix ids for cost parameters when special characters are included

- docs/source/whatsnew/1.0.0rc1.rst
- solarforecastarbiter/reports/figures/plotly_figures.py
Fixes issue where long probabilistic forecast names are cut off below the x axis. This sets a static height of 600 pixels and allows automargin to determine the space needed below the plot. This still has the downside of squeezing the plot to the top left to properly align with the axis labels. However, of the few solutions I tried this worked best across all of them. Screenshot below of the plot layout.
I did try adding newlines in the labels, but with too many ticks, or too narrow a screen overlap occured.
> adjust margin for long x axis names

- docs/source/api.rst
- docs/source/whatsnew/1.0.0rc2.rst
- docs/source/whatsnew/index.rst
- solarforecastarbiter/reference_forecasts/main.py
- solarforecastarbiter/reference_forecasts/persistence.py
- solarforecastarbiter/reference_forecasts/tests/test_main.py
- solarforecastarbiter/reference_forecasts/tests/test_persistence.py
- solarforecastarbiter/tests/test_utils.py
- solarforecastarbiter/utils.py
Two questions: should day ahead persistence keep NaNs in the forecast or fail to make one? Should probabilistic forecast return empty series when there is no data or raise some error?
> Fix various persistence bugs

- docs/source/whatsnew/1.0.0rc2.rst
- requirements.txt
- setup.py
- solarforecastarbiter/reports/figures/plotly_figures.py
- solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
- solarforecastarbiter/reports/template.py
- solarforecastarbiter/reports/templates/html/body.html
- solarforecastarbiter/reports/tests/test_template.py
Part of #516 aims to plot probabilistic forecast with axis = y. I've created confidence intervals from the available percentiles by taking `2 * | x -50 |` of each percentile, so we can plot a partial confidence interval e.g. if the probabilistic forecast only includes constant values 5, 25 50. we can shade the areas between the 5 and 25 point as if they are within the 90% confidence interval, and between 25 and 50 as if they're within the 50% confidence interval. This could be confusing to users, as plots would suggests that data should only exist in the lower portion of that interval. 
The screenshot below shows a plot with two distributions and two constant values, where one distrbution `asym thingy` is just a copy of the other missing some constant values.
Needs a few more things …
> shaded plots for probabilistic percentile forecasts (axis='y')

- docs/source/api.rst
- docs/source/whatsnew/1.0.0rc3.rst
- solarforecastarbiter/metrics/probabilistic.py
- solarforecastarbiter/metrics/tests/test_calculator.py
- solarforecastarbiter/metrics/tests/test_probabilistic.py
Add Quantile Score and Quantile Skill Score for evaluating probabilistic
forecasts.
> metrics/probabilities: add quantile score

- solarforecastarbiter/metrics/preprocessing.py
I wanted to make sure I understand what preprocessing is currently doing with quality flags, resampling, and alignment before we change things, so I added a notes section to the `process_forecast_observations` docstring.
> preprocessing documentation

- solarforecastarbiter/datamodel.py
- solarforecastarbiter/io/fetch/tests/test_arm.py
- solarforecastarbiter/io/fetch/tests/test_eia.py
- solarforecastarbiter/io/fetch/tests/test_pvdaq.py
- solarforecastarbiter/io/tests/test_api.py
- solarforecastarbiter/io/utils.py
- solarforecastarbiter/metrics/probabilistic.py
- solarforecastarbiter/metrics/tests/test_preprocessing.py
- solarforecastarbiter/reports/figures/tests/test_bokeh_figures.py
- solarforecastarbiter/validation/tests/test_validator.py
- solarforecastarbiter/validation/validator.py
I recently learned about ``pyupgrade`` and thought I'd throw it at solarforecastarbiter to see what it catches. Mostly improvements, not sure about the doc formatting and the `IOError` vs. `OSError`.
```
pyupgrade --py38-plus solarforecastarbiter/**/[a-z]*.py
```
> pyupgrade --py38-plus

- requirements.txt
- solarforecastarbiter/pvmodel.py
pvlib 0.8.0 will be released later today (hopefully), so making sure that our CI is happy with the beta release.
It looks like there's only one API change to deal with this time. 
The big win for us is the `read_crn` fix https://github.com/pvlib/pvlib-python/issues/1025
fyi @cwhanse.
> pvlib 0.8.0

- docs/source/whatsnew/1.0.0rc3.rst
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/metrics/preprocessing.py
Adds new class variable `__blurb__` to the relevant datamodel objects. Then `preprocessing.resample_and_align` pulls this attribute instead of `type(fx).__name__`. I used the name "blurb" because it's similar to `datamodel.CATEGORY_BLURBS`, and I put it in dunderscores because 1. it's the same for all instances of the class, so should be a class variable and 2. I didn't want to clutter the primary object namespace.
I also considered:
* `isinstance` calls
* a dict with classes for the keys and friendly strings for the values. Would be accessed like `d[type(fx)]`
The class variable approach feels more robust to me, but maybe I'm missing something.
> add __blurb__ to fx, obs dataclasses. use in preprocess results dict

- solarforecastarbiter/reports/figures/plotly_figures.py
> fix scatter plot axis range sensitivity to legend width

- .github/workflows/publish.yml
> add workflow to publish package to pypi on 1.* tags

- docs/source/whatsnew/1.0.0rc3.rst
- solarforecastarbiter/reports/figures/plotly_figures.py
Here's a screenshot of the report included in #568 after adjustment. This should be in line with the plots pre- #519
> Fix report plotting for probabilistic forecasts with axis=x

- docs/source/whatsnew/1.0.0rc3.rst
- solarforecastarbiter/io/reference_observations/common.py
- solarforecastarbiter/io/reference_observations/tests/test_common.py
First, abbreviate Persistence to Pers. then start cutting whole words out of the site name
> adjust how reference forecast names are truncated

- docs/source/whatsnew/1.0.0rc3.rst
- solarforecastarbiter/io/reference_observations/srml.py
- solarforecastarbiter/io/reference_observations/tests/test_srml.py
- [] Tests added.
Gaps in SRML data have been caused by posting NaN when posting reference data. These NaN values exist because SRML files are prefilled through the given month with NaN values during the day and 0s at night. Posting the NaN values that occur between the last measurement and the end of the period we want to update causes the `/observations/{uuid}/values/latest` endpoint of the arbiter API to return the last timestamp filled with a NaN. The reference data update script then uses as the latest time as the start of the range to update. A simple call to `dropna` is insufficient because NaNs are also used to represent truly missing data.
This updates the `solarforecastarbiter.io.reference_observations.srml.fetch` function to slice data from start to end, and then slice again …
> update SRML data to strip trailing nans

- docs/source/api.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/validation/tasks.py
- solarforecastarbiter/validation/tests/test_validation_tasks.py
- solarforecastarbiter/validation/tests/test_validator.py
- solarforecastarbiter/validation/validator.py
Making a PR for concrete discussion but not committed to the current approach.
I added a new function `validation.tasks._solpos_night_resample` that calculates solar position at every minute to determine the nightime flag value using the fraction of daytime minutes within an interval. 
Timings from my laptop:
```python
start = '20200101T0000'
end = '20200331T2359'
index = pd.date_range(start=start, end=end, freq='1min', tz='UTC')
index_hrly = index[::60]
obs_data_3m = pd.DataFrame({'value': 1, 'quality_flag': 2}, index=index)
obs_data_hrly_3m = pd.DataFrame({'value': 1, 'quality_flag': 2}, index=index_hrly)
%timeit tasks._solpos_night(obs, obs_data_3m)
1.2 s ± 35.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit tasks._solpos_night(obs, obs_data_hrly_3m)
28 ms ± 540 µs per …
```
> nighttime validation task that accounts for interval length

- docs/source/whatsnew/1.0.0rc4.rst
- solarforecastarbiter/reports/figures/plotly_figures.py
- solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
Adjusted the `X_LABEL_HEIGHT_FACTOR` to work with the longest possible forecast name: A forecast name containing 13 4 letter words separated by spaces, + the 'Prob(f <= x)  = 100.0%' labelling added by the plotting code. I hit a few cases where Plotly tried to angle the x axis labels, which caused some labels to run off the right side of the plot. So I've forced the plot to display x axis labels vertically when there are more than 6 labels. .
> Adjust plotly x_label_height_factor

- docs/source/whatsnew/1.0.0rc4.rst
- solarforecastarbiter/reports/figures/plotly_figures.py
- solarforecastarbiter/reports/figures/tests/conftest.py
- solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
- solarforecastarbiter/reports/template.py
- solarforecastarbiter/reports/templates/html/body.html
- solarforecastarbiter/reports/tests/test_template.py
(https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.
This adjusts `reports.template.py` and `reports.figures.plotly_figures.py` to handle cases where a user has only partial permissions to read time series data for the objects in a report.
Also selectively defines the plotly json specs for timeseries, scatter plot, and probabilistic timeseries figures to avoid intervening in the dashboard.
Previous behavior was such that the plotting code would fail at different points due to missing `observation_values` or `forecast_values` fields on the pairs in `Report.processed_forecasts_observations`. This would sometimes only emit a warning and result in empty plots.
The new behavior introduced by this PR should:
- Create no plots if no …
> Adjust templating and plotting to allow for partial reports as returned by the API

- docs/source/whatsnew/1.0.0rc4.rst
- solarforecastarbiter/reports/templates/html/base.html
- solarforecastarbiter/reports/templates/html/body.html
- solarforecastarbiter/reports/templates/html/macros.j2
- solarforecastarbiter/reports/templates/html/metrics_meta_table.html
- solarforecastarbiter/reports/templates/html/obsfx_table.html
- solarforecastarbiter/reports/tests/test_macros.py
- solarforecastarbiter/reports/tests/test_template.py
Allows scrolling for tables that scale with the number of selected metrics/pairs/quality flags.
Here is a report rendered both ways:
With new scrolling: [post-scrolling.zip](https://github.com/SolarArbiter/solarforecastarbiter-core/files/5380758/post-scrolling.zip)
Without scrolling: [pre-scrolling.zip](https://github.com/SolarArbiter/solarforecastarbiter-core/files/5380760/pre-scrolling.zip)
> Report table styles

- docs/source/whatsnew/1.0.0rc4.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/io/reference_observations/common.py
- solarforecastarbiter/io/reference_observations/pvdaq_reference_sites.json
- solarforecastarbiter/io/reference_observations/srml_reference_sites.json
- solarforecastarbiter/io/reference_observations/tests/conftest.py
- solarforecastarbiter/io/reference_observations/tests/test_common.py
- solarforecastarbiter/tests/test_datamodel.py
but still required it to be set. This make sure a user thinks about it
before going with none and allows the Union[Observation, Forecast] to
determine the proper from_dict type. Also set the default uncertainty
for reference observations to None.
> Allow uncertainty to be null

- docs/source/whatsnew/1.0.0rc4.rst
- solarforecastarbiter/io/tests/test_io_utils.py
- solarforecastarbiter/io/utils.py
> fix ensure_timestamps raising on bad args

- docs/source/whatsnew/1.0.0rc4.rst
- solarforecastarbiter/reports/templates/html/pending.html
- solarforecastarbiter/tests/test_utils.py
- solarforecastarbiter/utils.py
and add a comment to request a report recompute if it isn't computed in 30 minutes for #526
> avoid report logs in sentry

- docs/source/whatsnew/1.0.0rc4.rst
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/tests/test_datamodel.py
> add constant_value_units for prob. forecasts

- docs/source/whatsnew/1.0.0rc4.rst
- solarforecastarbiter/reports/figures/plotly_figures.py
And make hover on total plots show the full name
> avoid stacking in total metric plots

- docs/source/api.rst
- docs/source/whatsnew/1.0.0rc4.rst
- solarforecastarbiter/io/api.py
- solarforecastarbiter/io/tests/test_api.py
- solarforecastarbiter/reports/tests/test_reports_main.py
Initial implementation of breaking large requests into individual requests to avoid timeouts/hitting api limits. @alorenzo175 what do you think of this approach? I've only adjusted `get_observation_values`
> break up large requests

- docs/source/api.rst
- docs/source/whatsnew/1.0.0rc4.rst
- solarforecastarbiter/metrics/probabilistic.py
- solarforecastarbiter/metrics/tests/test_calculator.py
- solarforecastarbiter/metrics/tests/test_probabilistic.py
Add skill score version of the CRPS metric, which shows the relative improvement (in terms of CRPS) between a forecast versus a reference forecast.
> metrics: add CRPSS

- solarforecastarbiter/metrics/tests/test_probabilistic.py
This PR is in response to discussion in PR #605:
Add tests for the situation in which the forecast (fx) and reference forecasts (ref) have unequal distribution, either a) the same number of CDF intervals but not the same intervals (e.g. [25, 75] and [50, 100]) or b) a different number of CDF intervals (e.g. [25, 50, 75] and [0, 20, 40, 60, 80, 100]). In these two cases, the expected behavior (currently) is that the CRPS is calculated for both the fx and ref, and then the CRPSS is calculated without any adjustments.
> metrics: test unequal dist for CRPSS

- solarforecastarbiter/metrics/preprocessing.py
- solarforecastarbiter/reports/tests/test_reports_main.py
- solarforecastarbiter/tests/test_utils.py
- solarforecastarbiter/utils.py
#597 didn't fully capture children loggers to prevent messages from getting to sentry
> make sure hijacking loggers also captures children

- docs/source/whatsnew/1.0.0.rst
- docs/source/whatsnew/index.rst
- solarforecastarbiter/metrics/preprocessing.py
- solarforecastarbiter/metrics/tests/test_preprocessing.py
I wonder if we should switch `x` to `o` (for observation) while we're at it. The metrics documentation uses `o`.
The naming function is only tested for recursion, so I didn't modify any tests. I suppose I *could* add one.
> fix issue with prob fx label

- docs/source/whatsnew/1.0.0.rst
- solarforecastarbiter/reports/templates/html/load_metadata.html
- solarforecastarbiter/reports/tests/test_jinja_templates.py
Fixes a bug where dumped report metadata json is not correctly escaped which causes the metadata download function to fail.
> Use tojson filter to escape nested json and html

- docs/source/whatsnew/1.0.0.rst
- solarforecastarbiter/reports/figures/plotly_figures.py
- solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
- solarforecastarbiter/reports/templates/html/body.html
Fixes a bug where the x_labels were mixed up do to implicit sorting by the DataFrame.groupby function. 
Also discovered that my test reports did not adequately cover #599 . The metrics preprocessing code suffixes names with numbers when there are duplicate forecast names, so null characters were never used. When the null values are used, the `JSON.parse` function chokes. due to improper encoding. Using the `tojson` filter here fixes that issue. 
It looks like Webkit (Opera and Chrome on ubuntu) are rendering the null characters, while FireFox does not. Screenshot below.
> Report total metric ordering

- docs/source/whatsnew/1.0.2.rst
- solarforecastarbiter/conftest.py
- solarforecastarbiter/io/reference_observations/tests/test_common.py
- solarforecastarbiter/io/tests/test_api.py
- solarforecastarbiter/io/tests/test_io_utils.py
- solarforecastarbiter/metrics/tests/test_preprocessing.py
- solarforecastarbiter/reference_forecasts/tests/test_forecast.py
- solarforecastarbiter/reference_forecasts/tests/test_persistence.py
- solarforecastarbiter/tests/test_utils.py
- solarforecastarbiter/validation/tests/test_validation_tasks.py
- solarforecastarbiter/validation/tests/test_validator.py
- ~[ ] Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.~
I saw two options:
1. make the test expectations for ``freq`` more explicit, or
2. increase the minimum pandas to 1.1 and add ``check_freq=False`` to a bunch of tests. Unfortunately, the ``check_freq`` kwarg was introduced in 1.1 with a default value of ``True`` while the previous hard-coded behavior was ``check_freq=False``.
I figured "explicit is better...". In some cases I set ``freq = None`` on the input series/dataframe index because we do not generally assume serially complete time series and therefore data returned by `api.py` does not have defined ``freq``.
> clean up freq expectations for pd>=1.1 compat

- docs/source/whatsnew/1.0.2.rst
- solarforecastarbiter/reports/templates/html/body.html
- solarforecastarbiter/reports/templates/pdf/base.tex
…available
I'm not sure about a test for this since reasonably we can only test if the code within the else block doesn't cause a problem. And it's uncommon to begin with. Here's a zip file with examples showing that it works. 
[no_total_warning_examples.zip](https://github.com/SolarArbiter/solarforecastarbiter-core/files/5857610/no_total_warning_examples.zip)
> reports display warnings instead of empty tables if no total metrics

- docs/source/whatsnew/1.0.2.rst
- solarforecastarbiter/validation/quality_mapping.py
I don't think we need more tests here. We already test this list works and I don't see the point of testing if elements are in it in convoluted ways.
> add stale, interpolated flags to discard before resample

- docs/source/whatsnew/1.0.2.rst
- solarforecastarbiter/validation/tests/test_validator.py
- solarforecastarbiter/validation/validator.py
Evaluates `detect_clearsky` in `validator.detect_clearsky_ghi` only on continuous not-NA periods. Previously, if one tried to validate a period with missing times from the index, no clearsky validation would take place at all. Another option would be to reindex the input to a set frequency and insert nans. The current approach avoids applying `detect_clearsky` to any NaN values at all, but may reduce the length of the series that `detect_clearsky` sees.
For example, the approach in this PR works like
```
ghi = pd.Series(data, index=[2020-01-01T12:00Z, 2020-01-01T12:15Z, 2020-01-01T13:00Z, 2020-01-01T13:15Z])
out = detect_clearsky(ghi[2020-01-01T12:00Z:2020-0101T12:15Z]) + 
detect_clearsky(ghi[2020-01-01T13:00Z:2020-01-01T13:15Z])
```
if reindexing were used instead, a longer series would …
> Add NaNs in detect_clearsky to work around observation gaps

- docs/source/whatsnew/1.0.2.rst
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/io/tests/test_api.py
- solarforecastarbiter/reports/main.py
- solarforecastarbiter/tests/test_datamodel.py
Needs more tests, but works
no tz specified in report parameters
America/Denver specified in report parameters
> implement report_parameters.timezone

- solarforecastarbiter/metrics/tests/test_preprocessing.py
- solarforecastarbiter/tests/test_pvmodel.py
- solarforecastarbiter/validation/tasks.py
- solarforecastarbiter/validation/validator.py
Created https://github.com/SolarArbiter/solarforecastarbiter-core/issues/685 to track need to address future pandas compatibility that e29d18a filters away.
> compatibility with new numpy and pandas

- .gitignore
- docs/source/whatsnew/1.0.2.rst
- solarforecastarbiter/metrics/preprocessing.py
- solarforecastarbiter/reports/figures/plotly_figures.py
The issue with the missing observations in time series plots is due to the fact that the processed observations are only plotted for the first instance of that processed observation. In the TA2 reports, the PNNL forecast is the first forecast/observation pair, so it gets the first pair index assigned to it during plotting. But that forecast has not yet been uploaded, so the observations are all dropped for that pair (recall missing forecasts are dropped on a forecast by forecast basis). And then there is nothing to plot.
This PR changes the observation plotting algorithm. The net result is that we plot the union of processed observations for all pairs.
Prod
This PR
I'm not aware of any good automated ways to test this.
> plot all observation values in time series

- docs/source/reference-forecasts.rst
- docs/source/whatsnew/1.0.2.rst
- ~Tests added.~
- ~Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).~
Also updates the whats new date.
> clarify auto reference forecasts are arbiter only

- docs/source/whatsnew/1.0.2.rst
- solarforecastarbiter/reports/templates/html/macros.j2
- solarforecastarbiter/reports/templates/html/obsfx_table.html
> Fix reference forecast links, add report timerange to links

- docs/source/whatsnew/1.0.3.rst
- docs/source/whatsnew/index.rst
- solarforecastarbiter/reports/template.py
- solarforecastarbiter/reports/tests/test_template.py
Bug was caused when checking `report.report_parameters.object_pairs` for event forecasts to set a list of correct summary table headers. The dashboard drops the `object_pairs` from reports before rendering to avoid having to load or insert metadata into the pairs since that data is available in the raw_report.
> Adjust summary table header forecast type check

- docs/source/whatsnew/1.0.3.rst
- solarforecastarbiter/reference_forecasts/persistence.py
- solarforecastarbiter/reference_forecasts/tests/test_persistence.py
pre fix:
post fix:
I confirmed that the modified test does fail unless the fix is implemented.
FYI @dplarson (not trying to cast blame - just thought you might like to know since you're continuing to work on similar problems!)
> fix prob pers time of day when interval_label=ending

- docs/source/whatsnew/1.0.5.rst
- solarforecastarbiter/reports/templates/html/body.html
- solarforecastarbiter/reports/templates/html/macros.j2
Removes the `<br>` tags included in csv headers for report timeseries downloads, and separates each timeseries into a separate download.  Triggering a bunch of subsequent data downloads is pretty jarring, so perhaps inserting links to download each one individually would be better?
We could use something like [JSZip](https://stuk.github.io/jszip/) to create a zip, but I that is complicated by the need to supply the library in downloaded copies and include it in dashboard rendered reports.
@wholmgren What do you think about adding links to download each timeseries individually?
> Fix headers and indexes of report timeseries downloads

- docs/source/api.rst
- docs/source/whatsnew/1.0.9.rst
- docs/source/whatsnew/index.rst
- setup.py
- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/io/api.py
- solarforecastarbiter/metrics/preprocessing.py
- solarforecastarbiter/metrics/tests/test_preprocessing.py
- solarforecastarbiter/reports/main.py
- solarforecastarbiter/reports/templates/html/body.html
- solarforecastarbiter/reports/templates/pdf/base.tex
- solarforecastarbiter/reports/tests/test_template.py
- solarforecastarbiter/tests/test_datamodel.py
Adds handling for excluding outage periods from a report. Counterpart to API PR https://github.com/SolarArbiter/solarforecastarbiter-api/pull/325.
Converts a collection of (start, end) values representing system outages into a collection of (start, end) values that represents the forecast values associated with any forecast submissions that fall within an outage.  Then we use the start, end values to mask out forecast *and* observation values from the report before applying quality flags or other validation. This is so that we don't mistakenly report values that were dropped due to an outage as missing.
> exclude report outage periods

- solarforecastarbiter/conftest.py
- solarforecastarbiter/datamodel.py
- solarforecastarbiter/reports/main.py
- solarforecastarbiter/reports/templates/html/body.html
- solarforecastarbiter/reports/templates/pdf/base.tex
- solarforecastarbiter/reports/tests/test_template.py
- solarforecastarbiter/tests/test_datamodel.py
…ed before last computation
- Follow up to #752  for fixing bugs before committing to a release
Fixes an issue where newly added outages show up in the table of outage data before they are actually used in the computed report. Limits outages shown on in the table to those created before the raw report was generated. I've done this by adding the optional `created_at` and `modified_at` properties to the TimePeriod field. But perhaps it's better to add `outages` to the raw report?
> Outage Tweaks

- docs/source/whatsnew/1.0.9.rst
- solarforecastarbiter/reports/template.py
- solarforecastarbiter/reports/templates/html/body.html
Incorportates jinja expression statement which allows use of `{% do <statement> %}` instead of `{{ <statement> }}` the latter of which prints the result of the expression. In the case of the list.append function, this was causing `None` to be printed to the page whenever the outage update warning was printed.
> Don't print result of outage append call in jinja template

- solarforecastarbiter/reports/figures/plotly_figures.py
- solarforecastarbiter/reports/main.py
Adds report step logging to help identify hangups and slow downs in the report process. Currently there are only logs from workers beginning and ending report computation jobs.
> Add report step logging

- docs/source/whatsnew/1.0.11.rst
- docs/source/whatsnew/index.rst
- solarforecastarbiter/cli.py
- solarforecastarbiter/conftest.py
- solarforecastarbiter/reports/figures/plotly_figures.py
- solarforecastarbiter/reports/tests/test_reports_main.py
- Follow up of #765 
Removes orca fixtures, doctstring notes, and cli.
Tested in dev by cloning the report Bondville IL report (https://dashboard.solarforecastarbiter.org/reports/cfdd7674-49f2-11ea-8b7f-0a580a8002e1) and adjusting the time range to 2020-01-01 00:00:00-06:00 - 2020-03-07 00:00:00-06:00. Recomputing 5 times, the Orca process took an average of 20 seconds for plot generation, and Kaleido took 5.
> Orca cleanup

- docs/source/whatsnew/1.0.12.rst
- docs/source/whatsnew/index.rst
- solarforecastarbiter/io/reference_observations/crn.py
- solarforecastarbiter/io/reference_observations/tests/test_crn.py
> Handle -99999 NaN for 6-character width fields in USCRN data

- docs/source/whatsnew/1.0.12.rst
- solarforecastarbiter/io/tests/test_api.py
Would be better to do this right, but parking this here in case we are desperate in the future.
> add xfails for posting forecasts

- docs/source/whatsnew/1.0.13.rst
- solarforecastarbiter/metrics/probabilistic.py
- solarforecastarbiter/metrics/tests/test_calculator.py
- solarforecastarbiter/metrics/tests/test_probabilistic.py
This PR addresses the issue identified in #779 regarding how the current implementation of the CRPS metric handles cases where the observation is outside the forecast support. For example, if the probabilistic forecasts predicts power values from 1 to 8 MW but the actual power is 10 MW. The core idea is to extend the forecast CDF so covers the observation, whether the observation is less than the minimum forecast (`obs < min fx`) or greater than the maximum forecast (`obs > max fx`).
This PR also updates the CRPS function docstring with improved equation rendering and notes on practical considerations related to calculating CRPS from discrete forecast CDFs.
Lastly, the CRPS calculation has been updated to use trapezoidal numerical integration (instead of rectangular integration). This …
> Metrics: make CRPS handle obs outside the fx support

- docs/source/whatsnew/1.0.14.rst
- solarforecastarbiter/datamodel.py
Add `load` as an allowed variable. Previously the datamodel only supported `net_load` as a variable and therefore made no distinction between (gross) load vs net load. One of the key differences is that load is generally defined as a non-negative measure of energy demand, while net load is the signed measured of energy demand import (positive values) vs export (negative values). This is a subtle but important difference, and supporting both variables (`load` and `net_load`) in the datamodel will enable better defined functionality for users. For example, when validating load data, negative values should be treated as erroroneous. But negative values net load data should be treated as valid.
> datamodel: add `load` as an allowed variable
