azure-pipelines.yml
requirements-test.txt

Set up CI with Azure Pipelines

---

.gitignore
README.md
azure-pipelines.yml
requirements-test.txt

Adds coverage and linting tests to the azure pipeline. We'll see what it looks like on the azure side...
also adds install instructions to readme file and the azure badge for convenience.

readme instructions, pipeline coverage, linting

---

requirements.txt
solarforecastarbiter/validation/tests/test_validator.py
solarforecastarbiter/validation/validator.py

Implement irradiance limit tests for QCRad algorithm.
Implement irradiance component test for QCRad algorithm.
Implement diffuse to GHI ratio test for QCRad.
Add limit test for air temperature and wind.

Limit and ratio tests

---

azure-pipelines.yml
environment.yml
setup.py

It's not pretty. Probably won't work the first time...
Reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=ubuntu-16-04

add azure job that uses conda

---

solarforecastarbiter/io/fetch/arm.py
solarforecastarbiter/io/fetch/tests/test_arm.py
solarforecastarbiter/io/fetch/tests/test_sandia.py

Updated ARM parser so that user must supply datastream name and a list of variables to parse. Provided `IRRAD_VARIABLES` and `MET_VARIABLES` to give users a starting point. These are the most commonly available variables as of the module's writing for an irradiance or meteorological datastream.

Arm parser

---

solarforecastarbiter/io/fetch/sandia.py
solarforecastarbiter/io/fetch/tests/test_sandia.py

localize sandia parser data to UTC

---

solarforecastarbiter/validation/tests/test_validator.py
solarforecastarbiter/validation/validator.py

Closes #16 
Uses solar zenith angle

add day/night flag

---

solarforecastarbiter/validation/tests/test_validator.py
solarforecastarbiter/validation/validator.py

Closes #21 
Functions check for constant difference (stale data) and constant slope (interpolated data)
Time steps are assumed to be equal.

Detect stale and interpolated data

---

azure-pipelines.yml
environment.yml
requirements-test.txt
requirements.txt
setup.py
solarforecastarbiter/conftest.py
solarforecastarbiter/io/fetch/__init__.py
solarforecastarbiter/io/fetch/nwp.py
solarforecastarbiter/io/fetch/tests/test_nwp.py
solarforecastarbiter/reference_forecasts/tests/test_forecast.py
solarforecastarbiter/reference_forecasts/tests/test_main.py
solarforecastarbiter/reference_forecasts/tests/test_models.py
solarforecastarbiter/tests/test_pvmodel.py
solarforecastarbiter/validation/tests/test_validator.py

use aiohttp to fetch forecasts from nomads, use wgrib2 to convert to netcdf, then reshape and compress. Files are about half the estimates in #10

Script to fetch NWP forecasts and convert to netcdf

---

solarforecastarbiter/io/fetch/nwp.py
solarforecastarbiter/io/fetch/tests/test_init.py
solarforecastarbiter/io/fetch/tests/test_nwp.py

asyncio really helps here, there > 2000 grib files to download for one run. To get this to work without major changes, basically run a loop to get and make nc files for each GEFS ensemble member.
closes #63

get GEFS forecasts

---

.coveragerc
requirements-test.txt
setup.py
solarforecastarbiter/conftest.py
solarforecastarbiter/datamodel.py
solarforecastarbiter/io/api.py
solarforecastarbiter/io/tests/test_api.py
solarforecastarbiter/io/tests/test_utils.py
solarforecastarbiter/io/utils.py
solarforecastarbiter/pvmodel.py
solarforecastarbiter/tests/test_datamodel.py

Subclass requests.Session to maintain a connection pool and keep the code simple and readable

add functions to get/post data from API

---

requirements.txt
solarforecastarbiter/io/nwp.py
solarforecastarbiter/reference_forecasts/models.py
solarforecastarbiter/reference_forecasts/tests/test_forecast.py
solarforecastarbiter/reference_forecasts/tests/test_main.py
solarforecastarbiter/reference_forecasts/tests/test_models.py

Closes #10 
Partially addresses #93.
To do:

implement nwp model loading

---

requirements.txt
setup.py
solarforecastarbiter/cli.py
solarforecastarbiter/io/api.py
solarforecastarbiter/io/tests/test_api.py
solarforecastarbiter/tests/test_cli.py
solarforecastarbiter/validation/tasks.py
solarforecastarbiter/validation/tests/test_validation_tasks.py

daily validation tasks

---

solarforecastarbiter/cli.py
solarforecastarbiter/io/fetch/__init__.py
solarforecastarbiter/io/fetch/nwp.py
solarforecastarbiter/tests/test_cli.py
solarforecastarbiter/validation/tasks.py

move fetch nwp to cli.py

---

solarforecastarbiter/reference_forecasts/forecast.py
solarforecastarbiter/reference_forecasts/models.py
solarforecastarbiter/reference_forecasts/tests/test_forecast.py
solarforecastarbiter/reference_forecasts/tests/test_main.py
solarforecastarbiter/reference_forecasts/tests/test_models.py

implement unmix_intervals

---

solarforecastarbiter/io/api.py
solarforecastarbiter/io/tests/test_api.py

include text of response in api http error

---

solarforecastarbiter/plotting/timeseries.py
solarforecastarbiter/plotting/utils.py

pass limit to align index for plotting

---

solarforecastarbiter/io/api.py
solarforecastarbiter/io/tests/test_api.py
solarforecastarbiter/io/tests/test_utils.py
solarforecastarbiter/io/utils.py
solarforecastarbiter/reference_forecasts/main.py
solarforecastarbiter/reference_forecasts/tests/test_main.py

add option to adjust to interval_label for get obs/fx values

---

solarforecastarbiter/reference_forecasts/main.py
solarforecastarbiter/reference_forecasts/tests/test_fx_utils.py
solarforecastarbiter/reference_forecasts/tests/test_main.py
solarforecastarbiter/reference_forecasts/utils.py

closes #147 
confirmed that new tests fail without the fix.

fix run_persistence start, end time issue

---

docs/source/whatsnew/1.0.0b.rst
solarforecastarbiter/cli.py
solarforecastarbiter/datamodel.py
solarforecastarbiter/reports/main.py
solarforecastarbiter/reports/template.py
solarforecastarbiter/reports/templates/template.md
solarforecastarbiter/tests/data/report_metadata.json
solarforecastarbiter/tests/test_cli.py

also partially addresses #165 
command line interface runs with a json file similar to what would be posted to the API. For example:
```json
{
"name": "test",
"report_parameters": {
"start": "2019-08-21T00:00:00Z",
"end": "2019-08-28T00:00:00Z",
"filters": [],
"metrics": [
"mae",
"mbe",
"rmse"
],
"object_pairs": [
["9f657636-7e49-11e9-b77f-0a580a8003e9", "31ae8548-9a07-11e9-b2f4-0a580a8003d5"],
["9f657636-7e49-11e9-b77f-0a580a8003e9", "77be10e8-9c22-11e9-a974-0a580a8003d5"]
]
}
}
```

minor report fixes, cli report interface

---

docs/source/whatsnew/1.0.0b.rst
solarforecastarbiter/reference_forecasts/main.py
solarforecastarbiter/validation/tasks.py
solarforecastarbiter/validation/validator.py

fix return/assignment of None, bad kwarg handling

---

docs/source/cli.rst
docs/source/index.rst
docs/source/whatsnew/1.0.0b.rst

cli doc page

---

docs/source/api.rst
docs/source/reference-forecasts.rst
docs/source/whatsnew/1.0.0b.rst
solarforecastarbiter/io/nwp.py
solarforecastarbiter/reference_forecasts/forecast.py
solarforecastarbiter/reference_forecasts/main.py
solarforecastarbiter/reference_forecasts/models.py
solarforecastarbiter/reference_forecasts/tests/test_main.py
solarforecastarbiter/reference_forecasts/tests/test_models.py

implement probabilistic forecast using GEFS

---

docs/source/whatsnew/1.0.0b.rst
solarforecastarbiter/validation/tests/test_validator.py
solarforecastarbiter/validation/validator.py

adjust air temp and wind speed validation limits

---

docs/source/api.rst
docs/source/conf.py
docs/source/reference-forecasts.rst
docs/source/whatsnew/1.0.0b.rst
solarforecastarbiter/io/utils.py
solarforecastarbiter/reference_forecasts/forecast.py
solarforecastarbiter/reference_forecasts/main.py
solarforecastarbiter/reference_forecasts/models.py
solarforecastarbiter/reference_forecasts/persistence.py
solarforecastarbiter/reference_forecasts/tests/test_forecast.py
solarforecastarbiter/reference_forecasts/tests/test_main.py
solarforecastarbiter/reference_forecasts/tests/test_models.py

account for interval label in reference NWP forecasts

---

docs/source/whatsnew/1.0.0b.rst
solarforecastarbiter/reports/metrics.py
solarforecastarbiter/reports/tests/test_metrics.py

fix monthly, daily, hourly metrics

---

docs/source/whatsnew/1.0.0b.rst
solarforecastarbiter/reports/main.py
solarforecastarbiter/reports/tests/test_reports_main.py

fix report data load cache check

---

docs/source/whatsnew/1.0.0b.rst
solarforecastarbiter/reference_forecasts/main.py

fix run_persistence window documentation

---

docs/source/whatsnew/1.0.0b.rst

Cleans up 1.0.0b whats new file for release.
Let's keep this open for other minor doc stuff.

finalize release

---

docs/source/whatsnew/1.0.0b.rst

fix whatsnew formatting

---

docs/source/api.rst
docs/source/whatsnew/1.0.0b2.rst
solarforecastarbiter/cli.py
solarforecastarbiter/conftest.py
solarforecastarbiter/datamodel.py
solarforecastarbiter/io/api.py
solarforecastarbiter/io/tests/test_api.py
solarforecastarbiter/tests/data/report_metadata.json
solarforecastarbiter/tests/test_cli.py
solarforecastarbiter/tests/test_datamodel.py

Fixes to report CLI and to/from dict

---

docs/source/whatsnew/1.0.0b3.rst
docs/source/whatsnew/index.rst
solarforecastarbiter/io/reference_observations/midc.py

MIDC csv parsing errors

---

docs/source/whatsnew/1.0.0b3.rst
solarforecastarbiter/reports/figures.py

- ~Tests added.~
-  ~Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.~

fix plot limits for newer metrics

---

docs/source/whatsnew/1.0.0b3.rst
solarforecastarbiter/conftest.py
solarforecastarbiter/datamodel.py
solarforecastarbiter/io/tests/test_api.py
solarforecastarbiter/metrics/calculator.py
solarforecastarbiter/metrics/tests/test_calculator.py
solarforecastarbiter/reports/figures.py
solarforecastarbiter/reports/template.py
solarforecastarbiter/reports/templates/metrics_date.md
solarforecastarbiter/reports/templates/metrics_hour.md
solarforecastarbiter/reports/templates/metrics_month.md
solarforecastarbiter/reports/templates/metrics_total.md
solarforecastarbiter/reports/templates/metrics_weekday.md
solarforecastarbiter/reports/templates/metrics_year.md
solarforecastarbiter/reports/templates/template.md
solarforecastarbiter/reports/tests/test_figures.py
solarforecastarbiter/reports/tests/test_reports_main.py
solarforecastarbiter/tests/test_datamodel.py

swap categories keys values, drop day of month category

---

docs/source/whatsnew/1.0.0b3.rst
solarforecastarbiter/reports/templates/template.md
solarforecastarbiter/tests/data/report_metadata.json
solarforecastarbiter/tests/test_cli.py

- [ x ] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
- [ x ] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

add link to html, gpg sig, fix toc spacing

---

docs/source/whatsnew/1.0.0b3.rst

Do I also need to apply this to the beta4 branch or are you guys going to merge those later? @alorenzo175?

add date to 1.0beta3

---

solarforecastarbiter/conftest.py
solarforecastarbiter/reports/template.py
solarforecastarbiter/reports/tests/test_figures.py
solarforecastarbiter/reports/tests/test_macros.py
solarforecastarbiter/reports/tests/test_template.py

add reports template.py testing

---

docs/source/whatsnew/1.0.0b4.rst
solarforecastarbiter/reports/figures.py
solarforecastarbiter/reports/tests/test_figures.py

fix scatter limits w/ nans 

---

azure-pipelines.yml
docs/source/api.rst
docs/source/whatsnew/1.0.0b4.rst
requirements-test.txt
solarforecastarbiter/conftest.py
solarforecastarbiter/reports/figures.py
solarforecastarbiter/reports/tests/test_figures.py
solarforecastarbiter/tests/test_cli.py

Log errors on failed SVG export

---

solarforecastarbiter/datamodel.py
solarforecastarbiter/tests/test_utils.py
solarforecastarbiter/utils.py

add checksum function to utils and add field to report metadata

---

docs/source/whatsnew/1.0.0b4.rst
solarforecastarbiter/datamodel.py
solarforecastarbiter/io/api.py
solarforecastarbiter/reports/figures.py
solarforecastarbiter/reports/main.py
solarforecastarbiter/reports/tests/test_figures.py
solarforecastarbiter/reports/tests/test_reports_main.py
solarforecastarbiter/tests/test_datamodel.py

Also post failure messages along with a failed status when computation fails.

Add missing report tests

---

docs/source/api.rst
docs/source/whatsnew/1.0.0b4.rst
solarforecastarbiter/cli.py
solarforecastarbiter/conftest.py
solarforecastarbiter/datamodel.py
solarforecastarbiter/io/api.py
solarforecastarbiter/io/tests/test_api.py
solarforecastarbiter/metrics/preprocessing.py
solarforecastarbiter/metrics/tests/test_preprocessing.py
solarforecastarbiter/reports/figures.py
solarforecastarbiter/reports/main.py
solarforecastarbiter/reports/templates/body.html
solarforecastarbiter/reports/templates/versions.html
solarforecastarbiter/reports/tests/test_figures.py
solarforecastarbiter/reports/tests/test_macros.py
solarforecastarbiter/reports/tests/test_reports_main.py
solarforecastarbiter/tests/data/report_metadata.json
solarforecastarbiter/tests/test_datamodel.py

Remove the ReportMetadata object and put parameters in ReportParameters

Slight modification of Report

---

docs/source/api.rst
docs/source/whatsnew/1.0.0b4.rst
docs/source/whatsnew/index.rst
solarforecastarbiter/datamodel.py
solarforecastarbiter/io/api.py
solarforecastarbiter/metrics/deterministic.py
solarforecastarbiter/metrics/valuation.py
solarforecastarbiter/reports/figures.py
solarforecastarbiter/utils.py

Beta 4 doc changes

---

docs/source/api.rst
docs/source/whatsnew/1.0.0b4.rst
solarforecastarbiter/io/api.py
solarforecastarbiter/io/tests/test_io_utils.py
solarforecastarbiter/io/utils.py

make load_report_values convienence function

---

docs/source/whatsnew/1.0.0b4.rst
solarforecastarbiter/metrics/preprocessing.py
solarforecastarbiter/metrics/tests/test_preprocessing.py
solarforecastarbiter/reports/templates/body.html
solarforecastarbiter/reports/templates/obsfx_table.html

make unique processed fxobs names and update tables

---

docs/source/whatsnew/1.0.0b4.rst
examples/Reference Report Creation.ipynb
solarforecastarbiter/datamodel.py
solarforecastarbiter/io/api.py
solarforecastarbiter/io/tests/test_api.py
solarforecastarbiter/reports/figures.py
solarforecastarbiter/tests/test_datamodel.py

And fix issues when creating a report with filters and figure name splitting

Add notebook to create reference reports

---

docs/source/whatsnew/1.0.0b4.rst

update beta4 date

---

docs/source/whatsnew/1.0.0b5.rst
docs/source/whatsnew/index.rst
solarforecastarbiter/io/reference_observations/srml.py
solarforecastarbiter/io/reference_observations/tests/test_srml.py

Fix fetching SRML

---

azure-pipelines.yml
docs/source/whatsnew/1.0.0b5.rst
solarforecastarbiter/cli.py
solarforecastarbiter/reports/figures.py
solarforecastarbiter/reports/tests/test_figures.py
solarforecastarbiter/tests/test_cli.py

Remove phantomjs in favor of chromedriver for SVG generation

---

setup.py
solarforecastarbiter/reports/figures/bokeh_figures.py

Adds dependencies for plotly plots to setup.py so they are included in install.

add plotly's dependencies to setup.py

---

docs/source/api.rst
docs/source/whatsnew/1.0.0b5.rst
solarforecastarbiter/reports/figures/plotly_figures.py
solarforecastarbiter/reports/figures/tests/test_plotly_figures.py
solarforecastarbiter/reports/template.py
solarforecastarbiter/reports/templates/body.html
solarforecastarbiter/reports/templates/head.html
solarforecastarbiter/reports/tests/test_template.py

Converts the timeseries and scatterplots of reports to plotly.

convert report timeseries to plotly

---

solarforecastarbiter/reports/figures/plotly_figures.py
solarforecastarbiter/reports/figures/tests/test_plotly_figures.py

Fixes a few bugs following conversion of timeseries plots to plotly.

Plotly timeseries bugs

---

docs/source/whatsnew/1.0.0b5.rst
solarforecastarbiter/conftest.py
solarforecastarbiter/datamodel.py
solarforecastarbiter/io/api.py
solarforecastarbiter/metrics/calculator.py
solarforecastarbiter/metrics/preprocessing.py
solarforecastarbiter/metrics/tests/test_calculator.py
solarforecastarbiter/tests/test_datamodel.py

fix normalization metrics in reports

---

docs/source/whatsnew/1.0.0b5.rst
solarforecastarbiter/io/tests/test_api.py
solarforecastarbiter/io/tests/test_io_utils.py
solarforecastarbiter/io/utils.py
solarforecastarbiter/validation/tasks.py
solarforecastarbiter/validation/tests/test_validation_tasks.py

Make sure API values are float/int and verify type before validation

---

solarforecastarbiter/reports/figures/plotly_figures.py
solarforecastarbiter/reports/figures/tests/test_plotly_figures.py

Convert report timeseries data to report timezone 

---

solarforecastarbiter/plotting/tests/test_plotting_utils.py
solarforecastarbiter/plotting/utils.py
solarforecastarbiter/reports/figures/plotly_figures.py

step plots with plotly

---

solarforecastarbiter/metrics/deterministic.py
solarforecastarbiter/metrics/tests/test_deterministic.py
solarforecastarbiter/reports/figures/plotly_figures.py
solarforecastarbiter/reports/main.py

fix package versions list

---

docs/source/whatsnew/1.0.0b5.rst
docs/source/whatsnew/1.0.0rc1.rst
docs/source/whatsnew/index.rst

update beta 5 whats new date, add empty rc1

---

docs/source/whatsnew/1.0.0rc1.rst
solarforecastarbiter/conftest.py
solarforecastarbiter/datamodel.py
solarforecastarbiter/io/reference_observations/rtc.py
solarforecastarbiter/pvmodel.py
solarforecastarbiter/reference_forecasts/main.py
solarforecastarbiter/reference_forecasts/tests/test_persistence.py
solarforecastarbiter/tests/test_pvmodel.py

convert temp coeff to %/C

---

docs/source/whatsnew/1.0.0rc1.rst
solarforecastarbiter/io/reference_observations/common.py
solarforecastarbiter/io/reference_observations/tests/test_common.py
solarforecastarbiter/validation/tasks.py
solarforecastarbiter/validation/tests/test_validation_tasks.py

And ensure that data is sorted before slicing from reference sources

Split daily validation posting on missing periods and week

---

docs/source/api.rst
docs/source/whatsnew/1.0.0rc1.rst
requirements-test.txt
solarforecastarbiter/cli.py
solarforecastarbiter/io/api.py
solarforecastarbiter/io/utils.py
solarforecastarbiter/tests/test_cli.py

Add option to report cli to roundtrip through serialization

---

solarforecastarbiter/io/reference_observations/pvdaq.py
solarforecastarbiter/io/reference_observations/tests/test_ref_pvdaq.py

fix pvdaq power units

---

packages.tex
solarforecastarbiter/datamodel.py
solarforecastarbiter/reports/template.py
solarforecastarbiter/reports/templates/pdf/base.tex
solarforecastarbiter/reports/templates/pdf/macros.j2
solarforecastarbiter/reports/tests/test_template.py

Fix PDF rendering w/ special characters

---

solarforecastarbiter/cli.py
solarforecastarbiter/validation/quality_mapping.py
solarforecastarbiter/validation/tests/test_quality_mapping.py

Only apply derived masks to validated data

---

docs/source/whatsnew/1.0.0b6.rst
docs/source/whatsnew/1.0.0rc1.rst
docs/source/whatsnew/index.rst
solarforecastarbiter/io/reference_observations/sfa_reference_sites.csv

Also fixes the timezones for the DOE RTC Sites

Beta 6 release

---

docs/source/api.rst
docs/source/whatsnew/1.0.0rc1.rst
solarforecastarbiter/conftest.py
solarforecastarbiter/datamodel.py
solarforecastarbiter/io/api.py
solarforecastarbiter/io/tests/test_api.py

add support for parsing climate zones from API

---

docs/source/whatsnew/1.0.0rc1.rst
solarforecastarbiter/io/api.py
solarforecastarbiter/io/tests/test_api.py

Forecast get mapping

---

docs/source/cost.rst
docs/source/whatsnew/1.0.0rc1.rst
solarforecastarbiter/reports/template.py
solarforecastarbiter/reports/templates/cost_params_text
solarforecastarbiter/reports/templates/html/body.html
solarforecastarbiter/reports/templates/html/head.html
solarforecastarbiter/reports/templates/html/metrics_meta_table.html
solarforecastarbiter/reports/templates/metrics_meta_table_text
solarforecastarbiter/reports/templates/pdf/base.tex
solarforecastarbiter/reports/templates/pdf/macros.j2
solarforecastarbiter/reports/tests/test_template.py

Add cost parameters to report body

---

solarforecastarbiter/reports/templates/html/macros.j2
solarforecastarbiter/reports/templates/pdf/macros.j2

add empty values to metrics table when no metric found

---

solarforecastarbiter/reports/template.py
solarforecastarbiter/reports/templates/html/body.html
solarforecastarbiter/reports/tests/test_template.py

fix metric figure div ids

---

docs/source/whatsnew/1.0.0rc1.rst
solarforecastarbiter/reports/templates/html/macros.j2
solarforecastarbiter/reports/templates/pdf/macros.j2

Fix report tables

---

docs/source/whatsnew/1.0.0rc2.rst

add rc2 date

---

docs/source/whatsnew/1.0.0rc3.rst
docs/source/whatsnew/index.rst

stub rc3 whats new file, primarily for testing readthedocs PR integration.

rc3 whatsnew

---

docs/source/api.rst
docs/source/whatsnew/1.0.0rc3.rst
solarforecastarbiter/metrics/deterministic.py
solarforecastarbiter/metrics/tests/test_deterministic.py

relative_euclidean_distance. more pearson tests

---

docs/source/whatsnew/1.0.0rc3.rst
solarforecastarbiter/io/api.py
solarforecastarbiter/io/tests/test_api.py

kwargs in request_cli_access_token

---

solarforecastarbiter/io/reference_observations/common.py
solarforecastarbiter/io/reference_observations/tests/test_common.py

fix abbreviation, no period allowed in name

---

docs/source/whatsnew/1.0.0rc3.rst

update rc3 release date

---

docs/source/whatsnew/1.0.0rc4.rst
solarforecastarbiter/tests/test_utils.py
solarforecastarbiter/utils.py

Aggregation missing data

---

LICENSES/XARRAY_LICENSE
docs/source/whatsnew/1.0.0rc4.rst
solarforecastarbiter/datamodel.py
solarforecastarbiter/metrics/calculator.py
solarforecastarbiter/metrics/tests/test_calculator.py

add seasons metric category

---

solarforecastarbiter/datamodel.py

primarily for API schema validation

add ALLOWED_QUALITY_FLAGS tuple

---

docs/source/whatsnew/1.0.0rc4.rst
requirements-test.txt
requirements.txt
setup.py
solarforecastarbiter/cli.py
solarforecastarbiter/io/fetch/__init__.py
solarforecastarbiter/io/fetch/tests/test_init.py
solarforecastarbiter/tests/test_cli.py

Use loky to manage processes when fetching nwp files

---

docs/source/whatsnew/1.0.0rc4.rst
solarforecastarbiter/conftest.py
solarforecastarbiter/datamodel.py
solarforecastarbiter/io/tests/test_api.py
solarforecastarbiter/reference_forecasts/main.py
solarforecastarbiter/reference_forecasts/tests/test_fx_utils.py
solarforecastarbiter/reference_forecasts/tests/test_main.py
solarforecastarbiter/reference_forecasts/tests/test_persistence.py
solarforecastarbiter/tests/test_datamodel.py
solarforecastarbiter/validation/tests/test_validation_tasks.py

validate interval label, value type, and aggregate type in datamodel

---

docs/source/whatsnew/1.0.0rc4.rst

update rc4 date

---

docs/source/api.rst
docs/source/whatsnew/1.0.0.rst
solarforecastarbiter/cli.py
solarforecastarbiter/io/reference_aggregates.py
solarforecastarbiter/io/reference_observations/srml_reference_sites.json
solarforecastarbiter/io/tests/test_reference_aggregates.py
solarforecastarbiter/tests/test_cli.py

add reference aggregates

---

docs/source/api.rst
docs/source/whatsnew/1.0.0.rst
solarforecastarbiter/cli.py
solarforecastarbiter/io/api.py
solarforecastarbiter/io/reference_observations/arm.py
solarforecastarbiter/io/reference_observations/bsrn.py
solarforecastarbiter/io/reference_observations/common.py
solarforecastarbiter/io/reference_observations/crn.py
solarforecastarbiter/io/reference_observations/eia.py
solarforecastarbiter/io/reference_observations/midc.py
solarforecastarbiter/io/reference_observations/pvdaq.py
solarforecastarbiter/io/reference_observations/reference_data.py
solarforecastarbiter/io/reference_observations/rtc.py
solarforecastarbiter/io/reference_observations/solrad.py
solarforecastarbiter/io/reference_observations/srml.py
solarforecastarbiter/io/reference_observations/surfrad.py
solarforecastarbiter/io/reference_observations/tests/test_common.py
solarforecastarbiter/io/reference_observations/tests/test_reference_data.py
solarforecastarbiter/io/tests/test_api.py
solarforecastarbiter/tests/test_utils.py
solarforecastarbiter/utils.py

CLI to backfill observation gaps

---

docs/source/api.rst
docs/source/whatsnew/1.0.0.rst
solarforecastarbiter/cli.py
solarforecastarbiter/io/api.py
solarforecastarbiter/io/tests/test_api.py
solarforecastarbiter/reference_forecasts/main.py
solarforecastarbiter/reference_forecasts/tests/test_main.py
solarforecastarbiter/tests/test_cli.py

Support filling forecast gaps

---

docs/source/whatsnew/1.0.0.rst

update 1.0 date

---

docs/source/whatsnew/1.0.1.rst
docs/source/whatsnew/index.rst
solarforecastarbiter/reports/templates/html/body.html
solarforecastarbiter/reports/templates/pdf/base.tex

Let's double check that rtd renders the whats new correctly...

minor report text edits

---

docs/source/whatsnew/1.0.2.rst
solarforecastarbiter/reports/templates/html/body.html
solarforecastarbiter/reports/templates/pdf/base.tex

remove solar specific text from body.html and base.text

---

docs/source/whatsnew/1.0.2.rst
solarforecastarbiter/io/fetch/nwp.py

fix GFS dir for March 22 2021 12Z model upgrade

---

build/Dockerfile

and avoid possible table overflow errors

Keep texlive 2020 (vs 2021)

---

.github/workflows/main.yml
setup.py

fix ci test TEX repo

---

docs/source/whatsnew/1.0.3.rst
solarforecastarbiter/reports/figures/plotly_figures.py
solarforecastarbiter/reports/figures/tests/test_plotly_figures.py

~~- [ ] Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.~~

Add Interval length and label to report observation labels

---

docs/source/whatsnew/1.0.3.rst

update whatsnew for 1.0.3

---

docs/source/whatsnew/1.0.4.rst
docs/source/whatsnew/index.rst
solarforecastarbiter/metrics/preprocessing.py
solarforecastarbiter/metrics/tests/test_preprocessing.py
solarforecastarbiter/reports/figures/plotly_figures.py

fix resampling of obs when fx has different interval label

---

docs/source/whatsnew/1.0.4.rst

update whatsnew for v1.0.4

---

docs/source/whatsnew/1.0.5.rst
docs/source/whatsnew/index.rst
solarforecastarbiter/pvmodel.py
solarforecastarbiter/reference_forecasts/tests/test_persistence.py
solarforecastarbiter/tests/test_pvmodel.py

fix DNI projection into POA

---

docs/source/whatsnew/1.0.5.rst
requirements.txt
setup.py

add missing jinja2, pytz dependencies

---

docs/source/whatsnew/1.0.5.rst
solarforecastarbiter/cli.py
solarforecastarbiter/reference_forecasts/main.py
solarforecastarbiter/reference_forecasts/tests/test_fx_utils.py
solarforecastarbiter/reference_forecasts/utils.py

Reference forecast limit

---

docs/source/whatsnew/1.0.5.rst
solarforecastarbiter/metrics/preprocessing.py
solarforecastarbiter/metrics/tests/test_preprocessing.py

Use greater than or equal to in resample check

---

docs/source/whatsnew/1.0.5.rst
setup.py

Finalize 1.0.5 whats new

---

docs/source/reference-forecasts.rst
docs/source/whatsnew/1.0.6.rst

add prob pers to ref fx docs

---

docs/source/whatsnew/1.0.8.rst
docs/source/whatsnew/index.rst

Add an empty whatsnew for 1.0.8

add 108 whatsnew

---

docs/source/whatsnew/1.0.10.rst
docs/source/whatsnew/index.rst
solarforecastarbiter/reference_forecasts/persistence.py
solarforecastarbiter/reference_forecasts/tests/test_persistence.py

use nanpercentile in persistence ensemble functions

---

.codecov.yml
docs/source/conf.py
docs/source/whatsnew/1.0.14.rst
docs/source/whatsnew/index.rst
setup.py
solarforecastarbiter/reports/figures/plotly_figures.py
solarforecastarbiter/reports/templates/html/body.html
solarforecastarbiter/reports/templates/html/macros.j2
solarforecastarbiter/reports/templates/html/metrics_meta_table.html
solarforecastarbiter/reports/tests/test_macros.py

Add table and figure sorting, see #796

Sort tables and graphs
